### PR TITLE
Add module name and fix docstring, add datatype `dict` and some other changes

### PR DESCRIPTION
**Pull request by parsampsh**

### CODE REVIEW

**Comment by sami2020pro** [comment]
I need an explanation for **CHANGELOG.md** if you can write an explanation about your `pull request` and send it here.

**Comment by parsampsh** [comment]
> I need an explanation for **CHANGELOG.md** if you can write an explanation about your `pull request` and send it here.

Sure. i'll do this later.

**Comment by parsampsh** [comment]
Done.

**Comment by sami2020pro** [comment]
Thank you for P.R and help :heart:

**Pull request merged**
