### PR TITLE
fix: fix install script

### PR DESCRIPTION
**Pull request by parsampsh**

### CODE REVIEW

**Comment by sami2020pro** [comment]
I did'nt understand what the first line was doing (install file), can you explain that?

**Comment by parsampsh** [comment]
> I did'nt understand what the first line was doing (install file), can you explain that?

directory `/usr/share/nano/extra` may not be exists by default. the first line creates it (if not exixts).

**Comment by sami2020pro** [comment]
> > I did'nt understand what the first line was doing (install file), can you explain that?
> 
> directory `/usr/share/nano/extra` may not be exists by default. the first line creates it (if not exixts).

Aha, Nice.

**Comment by sami2020pro** [comment]
Thank you for P.R and help :heart:

**Pull request merged**
