### PR TITLE
Update pashmak.nanorc

### PR DESCRIPTION
**Pull request by adabadadudu**
in the new Pashmak version end keyword added to pashmak see  https://github.com/pashmaklang/pashmak/issues/151

### CODE REVIEW

**Comment by parsampsh** [comment]
Hi, currently i have no plan to start adding this, so don't merge this for now.

**Comment by adabadadudu** [comment]
> Hi, currently i have no plan to start adding this, so don't merge this for now.

Okay I wait for later :)

**Comment by sami2020pro** [comment]
What to do now:grey_question:

**Comment by adabadadudu** [comment]
> What to do now

wait

**Comment by sami2020pro** [comment]
OK:ok:

**Comment by adabadadudu** [comment]
Ok. now this feature does exist in Pashmak (<https://github.com/pashmaklang/pashmak/pull/171>).
so is it allowed to merge this PR?

**Comment by parsampsh** [comment]
> Ok. now this feature does exist in Pashmak ([pashmaklang/pashmak#171](https://github.com/pashmaklang/pashmak/pull/171)). so is it allowed to merge this PR?

Yeah it is.

**Comment by sami2020pro** [comment]
Hi, I wasn't available for a while.

I merged the pull request. If there is any problem, Just mention it to fix it.

**Comment by parsampsh** [comment]
@sami2020pro Welcome back buddy :)

**Pull request merged**
